FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY requirements-webui.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-webui.txt

COPY . .

RUN mkdir -p /app/video

VOLUME ["/app/video"]

CMD ["sh", "-c", "python webui.py & python main.py"]